"""app/services/recommendation_service.py

Recommendation Service:
- Ingestion and persistent storage of AI/Risk recommendations
- Human-in-the-loop decision lifecycle (APPROVE, MODIFY, REJECT)
- Complete decision auditing with controller identity and timestamps
- Real-time WebSocket broadcasting to connected station operators
"""

import asyncio
import logging
from datetime import datetime, timezone
from typing import List, Optional
from sqlalchemy.orm import Session

from app.models.recommendation import (
    Recommendation,
    RecommendationStatus,
    RecommendationSeverity,
    RecommendationAudit,
)
from app.models.station import Station
from app.models.user import User
from app.schemas.recommendation import (
    RecommendationCreate,
    RecommendationApproveRequest,
    RecommendationModifyRequest,
    RecommendationRejectRequest,
)
from app.websockets.manager import ws_manager

logger = logging.getLogger(__name__)


def _safe_ws_broadcast(coro):
    """Safely schedule an async WebSocket broadcast from sync or async context."""
    try:
        loop = asyncio.get_event_loop()
        if loop.is_running():
            asyncio.create_task(coro)
        else:
            loop.run_until_complete(coro)
    except RuntimeError:
        asyncio.run(coro)
    except Exception as exc:
        logger.error("Failed to broadcast WebSocket recommendation event: %s", exc)


def _broadcast_recommendation_event(station_code: str, rec: Recommendation, action: str) -> None:
    """Broadcast real-time recommendation updates over WebSocket."""
    status_str = rec.status.value if hasattr(rec.status, "value") else str(rec.status)
    event_payload = {
        "type": "recommendation",
        "action": action,
        "station_id": station_code.lower(),
        "recommendation_id": rec.id,
        "title": rec.title,
        "severity": rec.severity.value if hasattr(rec.severity, "value") else str(rec.severity),
        "recommendations": [rec.modified_action or rec.recommended_action],
        "confidence": rec.confidence,
        "status": status_str,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    _safe_ws_broadcast(ws_manager.broadcast_to_station(station_code.lower(), event_payload))


def create_recommendation(payload: RecommendationCreate, db: Session) -> Recommendation:
    """Store an AI/Risk recommendation and initiate audit trail."""
    sev_str = payload.severity.lower()
    try:
        severity = RecommendationSeverity(sev_str)
    except ValueError:
        severity = RecommendationSeverity.MEDIUM

    rec = Recommendation(
        station_id=payload.station_id,
        type=payload.type,
        severity=severity,
        title=payload.title,
        reason=payload.reason,
        recommended_action=payload.recommended_action,
        confidence=payload.confidence,
        status=RecommendationStatus.PENDING,
    )
    db.add(rec)
    db.commit()
    db.refresh(rec)

    # Initial audit entry
    audit = RecommendationAudit(
        recommendation_id=rec.id,
        user_id=None,
        action="CREATED",
        previous_status=None,
        new_status=RecommendationStatus.PENDING.value,
        notes="Generated by analytical / digital twin pipeline",
    )
    db.add(audit)
    db.commit()
    db.refresh(rec)

    station = db.query(Station).filter(Station.id == rec.station_id).first()
    station_code = station.code if station else f"STATION-{rec.station_id}"
    _broadcast_recommendation_event(station_code, rec, action="created")
    logger.info("Recommendation ID %d created for station %s", rec.id, station_code)
    return rec


def get_station_recommendations(
    station_id: int,
    status_filter: Optional[str],
    db: Session,
) -> List[Recommendation]:
    """Retrieve recommendations for a station with optional status filter."""
    query = db.query(Recommendation).filter(Recommendation.station_id == station_id)
    if status_filter:
        norm = status_filter.strip().upper()
        query = query.filter(Recommendation.status == norm)
    return query.order_by(Recommendation.created_at.desc()).all()


def get_recommendation_by_id(rec_id: int, db: Session) -> Optional[Recommendation]:
    """Fetch recommendation by primary key ID."""
    return db.query(Recommendation).filter(Recommendation.id == rec_id).first()


def approve_recommendation(
    rec_id: int,
    user: User,
    data: Optional[RecommendationApproveRequest],
    db: Session,
) -> Optional[Recommendation]:
    """Controller approves recommendation. Record decision and audit log."""
    rec = get_recommendation_by_id(rec_id, db)
    if not rec:
        return None

    prev_status = rec.status.value if hasattr(rec.status, "value") else str(rec.status)
    now = datetime.now(timezone.utc)
    rec.status = RecommendationStatus.APPROVED
    rec.decided_by = user.id
    rec.decided_at = now
    rec.decision_notes = data.notes if data else None
    rec.updated_at = now

    audit = RecommendationAudit(
        recommendation_id=rec.id,
        user_id=user.id,
        action="APPROVE",
        previous_status=prev_status,
        new_status=RecommendationStatus.APPROVED.value,
        notes=rec.decision_notes or f"Approved by {user.username}",
        timestamp=now,
    )
    db.add(audit)
    db.commit()
    db.refresh(rec)

    station = db.query(Station).filter(Station.id == rec.station_id).first()
    station_code = station.code if station else f"STATION-{rec.station_id}"
    _broadcast_recommendation_event(station_code, rec, action="approved")
    logger.info("Recommendation ID %d APPROVED by user %s", rec.id, user.username)
    return rec


def modify_recommendation(
    rec_id: int,
    user: User,
    data: RecommendationModifyRequest,
    db: Session,
) -> Optional[Recommendation]:
    """Controller modifies recommendation action. Record changes and audit log."""
    rec = get_recommendation_by_id(rec_id, db)
    if not rec:
        return None

    prev_status = rec.status.value if hasattr(rec.status, "value") else str(rec.status)
    now = datetime.now(timezone.utc)
    rec.status = RecommendationStatus.MODIFIED
    rec.modified_action = data.modified_action
    rec.decided_by = user.id
    rec.decided_at = now
    rec.decision_notes = data.notes
    rec.updated_at = now

    audit = RecommendationAudit(
        recommendation_id=rec.id,
        user_id=user.id,
        action="MODIFY",
        previous_status=prev_status,
        new_status=RecommendationStatus.MODIFIED.value,
        notes=f"Modified by {user.username}: {data.modified_action} (Notes: {data.notes})",
        timestamp=now,
    )
    db.add(audit)
    db.commit()
    db.refresh(rec)

    station = db.query(Station).filter(Station.id == rec.station_id).first()
    station_code = station.code if station else f"STATION-{rec.station_id}"
    _broadcast_recommendation_event(station_code, rec, action="modified")
    logger.info("Recommendation ID %d MODIFIED by user %s", rec.id, user.username)
    return rec


def reject_recommendation(
    rec_id: int,
    user: User,
    data: RecommendationRejectRequest,
    db: Session,
) -> Optional[Recommendation]:
    """Controller rejects recommendation. Record rejection reason and audit log."""
    rec = get_recommendation_by_id(rec_id, db)
    if not rec:
        return None

    prev_status = rec.status.value if hasattr(rec.status, "value") else str(rec.status)
    now = datetime.now(timezone.utc)
    rec.status = RecommendationStatus.REJECTED
    rec.decided_by = user.id
    rec.decided_at = now
    rec.decision_notes = data.reason
    rec.updated_at = now

    audit = RecommendationAudit(
        recommendation_id=rec.id,
        user_id=user.id,
        action="REJECT",
        previous_status=prev_status,
        new_status=RecommendationStatus.REJECTED.value,
        notes=f"Rejected by {user.username}. Reason: {data.reason}",
        timestamp=now,
    )
    db.add(audit)
    db.commit()
    db.refresh(rec)

    station = db.query(Station).filter(Station.id == rec.station_id).first()
    station_code = station.code if station else f"STATION-{rec.station_id}"
    _broadcast_recommendation_event(station_code, rec, action="rejected")
    logger.info("Recommendation ID %d REJECTED by user %s", rec.id, user.username)
    return rec
